-- MySQL Script generated by MySQL Workbench
-- 12/17/23 04:31:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbasochipo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbasochipo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbasochipo` DEFAULT CHARACTER SET utf8mb4 ;
USE `dbasochipo` ;

-- -----------------------------------------------------
-- Table `dbasochipo`.`tbl_actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`tbl_actividades` (
  `Act_id` INT(11) NOT NULL AUTO_INCREMENT,
  `MeDi_id` INT(11) NULL DEFAULT NULL,
  `MeDi_id1` INT(11) NULL DEFAULT NULL,
  `MeDi_id2` INT(11) NULL DEFAULT NULL,
  `MeDi_id3` INT(11) NULL DEFAULT NULL,
  `MeDi_id4` INT(11) NULL DEFAULT NULL,
  `Act_Nombre` VARCHAR(100) NULL DEFAULT NULL,
  `Act_descripcion` LONGTEXT NULL DEFAULT NULL,
  `Act_fecha` DATETIME NULL DEFAULT NULL,
  `Act_estado` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`Act_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbasochipo`.`tbl_estado_civil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`tbl_estado_civil` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `dbasochipo`.`tbl_departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`tbl_departamentos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `dbasochipo`.`tbl_ciudades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`tbl_ciudades` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `departamento_id` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ciudad_departamento_idx` (`departamento_id` ASC),
  CONSTRAINT `fk_ciudad_departamento`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `dbasochipo`.`tbl_departamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `dbasochipo`.`tbl_miembros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`tbl_miembros` (
  `Mi_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Mi_Nombres` VARCHAR(120) NULL DEFAULT NULL,
  `Mi_Apellido` VARCHAR(120) NULL DEFAULT NULL,
  `Mi_FechaNacimiento` DATE NULL DEFAULT NULL,
  `Mi_Celular` VARCHAR(100) NULL DEFAULT NULL,
  `Mi_Email` VARCHAR(100) NULL DEFAULT NULL,
  `ciudad_id` INT(11) NULL DEFAULT NULL,
  `Mi_Ocupacion` VARCHAR(100) NULL DEFAULT NULL,
  `Mi_Direccion` VARCHAR(200) NULL DEFAULT NULL,
  `Mi_tiempo` VARCHAR(50) NULL DEFAULT NULL,
  `CI` VARCHAR(50) NULL DEFAULT NULL,
  `estado_civil_id` INT(11) NULL DEFAULT NULL,
  `CarnetDiscapacidad` VARCHAR(50) NULL DEFAULT NULL,
  `imagen` VARCHAR(50) NOT NULL,
  `Mi_Estado` ENUM('Activo','Inactivo') NOT NULL DEFAULT 'Activo',
  PRIMARY KEY (`Mi_id`),
  INDEX `CI_idx` (`CI` ASC),
  INDEX `fk_miembros_ciudad_idx` (`ciudad_id` ASC),
  INDEX `fk_miembros_estado_civil_idx` (`estado_civil_id` ASC),
  CONSTRAINT `fk_miembros_ciudad`
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `dbasochipo`.`tbl_ciudades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_miembros_estado_civil`
    FOREIGN KEY (`estado_civil_id`)
    REFERENCES `dbasochipo`.`tbl_estado_civil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbasochipo`.`tbl_apoyo_miembros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`tbl_apoyo_miembros` (
  `ApoMi_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Mi_id` INT(11) NOT NULL,
  `TiApo` VARCHAR(100) NULL DEFAULT NULL,
  `ApoMi_Cantidad` DOUBLE NULL DEFAULT NULL,
  `ApoMi_Observaciones` LONGTEXT NULL DEFAULT NULL,
  `ApoMi_registro` DATE NULL DEFAULT NULL,
  `condicion` TINYINT(4) NOT NULL,
  PRIMARY KEY (`ApoMi_id`),
  INDEX `apoyo_miembros_idx` (`Mi_id` ASC),
  CONSTRAINT `fk_apoyo_miembros`
    FOREIGN KEY (`Mi_id`)
    REFERENCES `dbasochipo`.`tbl_miembros` (`Mi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbasochipo`.`tbl_auspiciantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`tbl_auspiciantes` (
  `aus_id` INT(11) NOT NULL AUTO_INCREMENT,
  `aus_Nombre` VARCHAR(200) NULL DEFAULT NULL,
  `aus_pais` VARCHAR(50) NULL DEFAULT NULL,
  `aus_departamento` VARCHAR(50) NULL DEFAULT NULL,
  `aus_ciudad` VARCHAR(100) NULL DEFAULT NULL,
  `Otro_dato` VARCHAR(200) NULL DEFAULT NULL,
  `imagen` VARCHAR(50) NOT NULL,
  `condicion` TINYINT(4) NOT NULL,
  PRIMARY KEY (`aus_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbasochipo`.`tbl_cuotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`tbl_cuotas` (
  `Cuo_Id` INT(11) NOT NULL AUTO_INCREMENT,
  `MeDi_id` INT(11) NULL DEFAULT NULL,
  `Cuo_Monto` DECIMAL(10,2) NULL DEFAULT NULL,
  `Cuo_fechaPago` DATETIME NULL DEFAULT NULL,
  `Cuo_Pagado` TINYINT(1) NULL DEFAULT NULL,
  `Cuo_Observaciones` LONGTEXT NULL DEFAULT NULL,
  `Cuo_registro` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Cuo_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbasochipo`.`tbl_especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`tbl_especialidad` (
  `Esp_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Esp_Nombre` VARCHAR(100) NULL DEFAULT NULL,
  `Esp_Descripcion` LONGTEXT NULL DEFAULT NULL,
  `Esp_Registro` DATETIME NULL DEFAULT NULL,
  `Esp_Modificacion` DATETIME NULL DEFAULT NULL,
  `Esp_Eliminacion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Esp_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbasochipo`.`tbl_especialidad_miembros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`tbl_especialidad_miembros` (
  `EspMi_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Mi_id` INT(11) NULL DEFAULT NULL,
  `Esp_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`EspMi_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbasochipo`.`tbl_hipoacusiamiembros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`tbl_hipoacusiamiembros` (
  `hipoMi_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Mi_id` INT(11) NULL DEFAULT NULL,
  `hipo_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`hipoMi_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbasochipo`.`tbl_inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`tbl_inventario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipoProducto` INT(11) NULL DEFAULT NULL,
  `producto` VARCHAR(200) NULL DEFAULT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `fechaRegistro` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbasochipo`.`tbl_mesa_directiva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`tbl_mesa_directiva` (
  `MeDi_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Mi_id` INT NOT NULL,
  `cargo` VARCHAR(80) NOT NULL,
  `MeDi_FechaInicioFunciones` DATE NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `clave` VARCHAR(64) NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `condicion` TINYINT(4) NOT NULL,
  PRIMARY KEY (`MeDi_id`),
  INDEX `fk_mesadirectiva_miembros_idx` (`Mi_id` ASC),
  CONSTRAINT `fk_mesadirectiva_miembros`
    FOREIGN KEY (`Mi_id`)
    REFERENCES `dbasochipo`.`tbl_miembros` (`Mi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbasochipo`.`tbl_montos_auspiciantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`tbl_montos_auspiciantes` (
  `MonAus_id` INT(11) NOT NULL AUTO_INCREMENT,
  `MeDi_id` INT(11) NOT NULL,
  `MonAus_Monto` DECIMAL(10,2) NULL DEFAULT NULL,
  `MonAus_Inicio` DATE NULL DEFAULT NULL,
  `MonAus_Cierre` DATE NULL DEFAULT NULL,
  `MonAus_Observaciones` LONGTEXT NULL DEFAULT NULL,
  `Aus_id` INT(11) NOT NULL,
  `factura` VARCHAR(50) NOT NULL,
  `condicion` TINYINT(4) NOT NULL,
  PRIMARY KEY (`MonAus_id`),
  INDEX `fk_auspiciante_idx` (`MeDi_id` ASC),
  CONSTRAINT `fk_auspiciante`
    FOREIGN KEY (`MeDi_id`)
    REFERENCES `dbasochipo`.`tbl_auspiciantes` (`aus_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mesa_directiva`
    FOREIGN KEY (`MeDi_id`)
    REFERENCES `dbasochipo`.`tbl_mesa_directiva` (`MeDi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbasochipo`.`tbl_multasmesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`tbl_multasmesa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idMiembro` INT(11) NULL DEFAULT NULL,
  `observaciones` VARCHAR(800) NULL DEFAULT NULL,
  `cant` DOUBLE NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `fechaRegistro` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbasochipo`.`tbl_ocupacionmiembros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`tbl_ocupacionmiembros` (
  `Ocu_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Ocu_Nombre` VARCHAR(200) NULL DEFAULT NULL,
  `Ocu_Descripcion` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Ocu_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbasochipo`.`tbl_participacionmiembros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`tbl_participacionmiembros` (
  `ParMi_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Act_id` INT(11) NULL DEFAULT NULL,
  `Mi_Id` INT(11) NULL DEFAULT NULL,
  `ParMi_tipo` LONGTEXT NULL DEFAULT NULL,
  `ParMi_observaciones` LONGTEXT NULL DEFAULT NULL,
  `ParMi_Activo` TINYINT(1) NULL DEFAULT NULL,
  `ParMi_Registro` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ParMi_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbasochipo`.`tbl_tipoproducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`tbl_tipoproducto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbasochipo`.`tbl_tipos_apoyo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`tbl_tipos_apoyo` (
  `TiApo_id` INT(11) NOT NULL AUTO_INCREMENT,
  `TiApo_nombre` VARCHAR(200) NULL DEFAULT NULL,
  `TiApo_Descripcion` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`TiApo_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbasochipo`.`tbl_tiposhipoacusia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`tbl_tiposhipoacusia` (
  `hipo_id` INT(11) NOT NULL AUTO_INCREMENT,
  `hipo_nombre` VARCHAR(200) NULL DEFAULT NULL,
  `hipo_Descripcion` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`hipo_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbasochipo`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`permiso` (
  `idpermiso` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpermiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbasochipo`.`usuario_permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbasochipo`.`usuario_permiso` (
  `idusuario_permiso` INT NOT NULL,
  `MeDi_id` INT NOT NULL,
  `idpermiso` INT NOT NULL,
  PRIMARY KEY (`idusuario_permiso`),
  INDEX `fk_usuariopermiso_mesadirectiva_idx` (`MeDi_id` ASC),
  INDEX `fk_usuariopermiso_permiso_idx` (`idpermiso` ASC),
  CONSTRAINT `fk_usuariopermiso_mesadirectiva`
    FOREIGN KEY (`MeDi_id`)
    REFERENCES `dbasochipo`.`tbl_mesa_directiva` (`Mi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuariopermiso_permiso`
    FOREIGN KEY (`idpermiso`)
    REFERENCES `dbasochipo`.`permiso` (`idpermiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
